# Enable the issue-845 fix
issue-845-fix: True

# Global mockery settings
with-expecter: true

# Packages configuration
packages:
  github.com/wot-oss/tmc/internal/app/http:
    interfaces:
      HandlerService:
        config:
          dir: "internal/app/http/mocks"
          mockname: "HandlerService"
          filename: "HandlerService.go"
          outpkg: mocks
  
  github.com/wot-oss/tmc/internal/repos:
    interfaces:
      Repo:
        config:
          dir: "internal/repos/mocks"
          mockname: "Repo"
          filename: "Repo.go"
          outpkg: mocks
      
      S3Client:
        config:
          dir: "internal/testutils/s3mocks"
          mockname: "S3Client"
          filename: "S3Client.go"
          outpkg: s3mocks