// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/wot-oss/tmc/internal/model"

	repos "github.com/wot-oss/tmc/internal/repos"
)

// MockHandlerService is an autogenerated mock type for the HandlerService type
type MockHandlerService struct {
	mock.Mock
}

type MockHandlerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandlerService) EXPECT() *MockHandlerService_Expecter {
	return &MockHandlerService_Expecter{mock: &_m.Mock}
}

// CheckHealth provides a mock function with given fields: ctx
func (_m *MockHandlerService) CheckHealth(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandlerService_CheckHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHealth'
type MockHandlerService_CheckHealth_Call struct {
	*mock.Call
}

// CheckHealth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHandlerService_Expecter) CheckHealth(ctx interface{}) *MockHandlerService_CheckHealth_Call {
	return &MockHandlerService_CheckHealth_Call{Call: _e.mock.On("CheckHealth", ctx)}
}

func (_c *MockHandlerService_CheckHealth_Call) Run(run func(ctx context.Context)) *MockHandlerService_CheckHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHandlerService_CheckHealth_Call) Return(_a0 error) *MockHandlerService_CheckHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerService_CheckHealth_Call) RunAndReturn(run func(context.Context) error) *MockHandlerService_CheckHealth_Call {
	_c.Call.Return(run)
	return _c
}

// CheckHealthLive provides a mock function with given fields: ctx
func (_m *MockHandlerService) CheckHealthLive(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealthLive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandlerService_CheckHealthLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHealthLive'
type MockHandlerService_CheckHealthLive_Call struct {
	*mock.Call
}

// CheckHealthLive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHandlerService_Expecter) CheckHealthLive(ctx interface{}) *MockHandlerService_CheckHealthLive_Call {
	return &MockHandlerService_CheckHealthLive_Call{Call: _e.mock.On("CheckHealthLive", ctx)}
}

func (_c *MockHandlerService_CheckHealthLive_Call) Run(run func(ctx context.Context)) *MockHandlerService_CheckHealthLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHandlerService_CheckHealthLive_Call) Return(_a0 error) *MockHandlerService_CheckHealthLive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerService_CheckHealthLive_Call) RunAndReturn(run func(context.Context) error) *MockHandlerService_CheckHealthLive_Call {
	_c.Call.Return(run)
	return _c
}

// CheckHealthReady provides a mock function with given fields: ctx
func (_m *MockHandlerService) CheckHealthReady(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealthReady")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandlerService_CheckHealthReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHealthReady'
type MockHandlerService_CheckHealthReady_Call struct {
	*mock.Call
}

// CheckHealthReady is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHandlerService_Expecter) CheckHealthReady(ctx interface{}) *MockHandlerService_CheckHealthReady_Call {
	return &MockHandlerService_CheckHealthReady_Call{Call: _e.mock.On("CheckHealthReady", ctx)}
}

func (_c *MockHandlerService_CheckHealthReady_Call) Run(run func(ctx context.Context)) *MockHandlerService_CheckHealthReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHandlerService_CheckHealthReady_Call) Return(_a0 error) *MockHandlerService_CheckHealthReady_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerService_CheckHealthReady_Call) RunAndReturn(run func(context.Context) error) *MockHandlerService_CheckHealthReady_Call {
	_c.Call.Return(run)
	return _c
}

// CheckHealthStartup provides a mock function with given fields: ctx
func (_m *MockHandlerService) CheckHealthStartup(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealthStartup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandlerService_CheckHealthStartup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHealthStartup'
type MockHandlerService_CheckHealthStartup_Call struct {
	*mock.Call
}

// CheckHealthStartup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHandlerService_Expecter) CheckHealthStartup(ctx interface{}) *MockHandlerService_CheckHealthStartup_Call {
	return &MockHandlerService_CheckHealthStartup_Call{Call: _e.mock.On("CheckHealthStartup", ctx)}
}

func (_c *MockHandlerService_CheckHealthStartup_Call) Run(run func(ctx context.Context)) *MockHandlerService_CheckHealthStartup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHandlerService_CheckHealthStartup_Call) Return(_a0 error) *MockHandlerService_CheckHealthStartup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerService_CheckHealthStartup_Call) RunAndReturn(run func(context.Context) error) *MockHandlerService_CheckHealthStartup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAttachment provides a mock function with given fields: ctx, repo, ref, attachmentFileName
func (_m *MockHandlerService) DeleteAttachment(ctx context.Context, repo string, ref model.AttachmentContainerRef, attachmentFileName string) error {
	ret := _m.Called(ctx, repo, ref, attachmentFileName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttachment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.AttachmentContainerRef, string) error); ok {
		r0 = rf(ctx, repo, ref, attachmentFileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandlerService_DeleteAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttachment'
type MockHandlerService_DeleteAttachment_Call struct {
	*mock.Call
}

// DeleteAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - ref model.AttachmentContainerRef
//   - attachmentFileName string
func (_e *MockHandlerService_Expecter) DeleteAttachment(ctx interface{}, repo interface{}, ref interface{}, attachmentFileName interface{}) *MockHandlerService_DeleteAttachment_Call {
	return &MockHandlerService_DeleteAttachment_Call{Call: _e.mock.On("DeleteAttachment", ctx, repo, ref, attachmentFileName)}
}

func (_c *MockHandlerService_DeleteAttachment_Call) Run(run func(ctx context.Context, repo string, ref model.AttachmentContainerRef, attachmentFileName string)) *MockHandlerService_DeleteAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.AttachmentContainerRef), args[3].(string))
	})
	return _c
}

func (_c *MockHandlerService_DeleteAttachment_Call) Return(_a0 error) *MockHandlerService_DeleteAttachment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerService_DeleteAttachment_Call) RunAndReturn(run func(context.Context, string, model.AttachmentContainerRef, string) error) *MockHandlerService_DeleteAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteThingModel provides a mock function with given fields: ctx, repo, tmID
func (_m *MockHandlerService) DeleteThingModel(ctx context.Context, repo string, tmID string) error {
	ret := _m.Called(ctx, repo, tmID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteThingModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, repo, tmID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandlerService_DeleteThingModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteThingModel'
type MockHandlerService_DeleteThingModel_Call struct {
	*mock.Call
}

// DeleteThingModel is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - tmID string
func (_e *MockHandlerService_Expecter) DeleteThingModel(ctx interface{}, repo interface{}, tmID interface{}) *MockHandlerService_DeleteThingModel_Call {
	return &MockHandlerService_DeleteThingModel_Call{Call: _e.mock.On("DeleteThingModel", ctx, repo, tmID)}
}

func (_c *MockHandlerService_DeleteThingModel_Call) Run(run func(ctx context.Context, repo string, tmID string)) *MockHandlerService_DeleteThingModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockHandlerService_DeleteThingModel_Call) Return(_a0 error) *MockHandlerService_DeleteThingModel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerService_DeleteThingModel_Call) RunAndReturn(run func(context.Context, string, string) error) *MockHandlerService_DeleteThingModel_Call {
	_c.Call.Return(run)
	return _c
}

// ExportCatalog provides a mock function with given fields: ctx, repo
func (_m *MockHandlerService) ExportCatalog(ctx context.Context, repo string) ([]byte, error) {
	ret := _m.Called(ctx, repo)

	if len(ret) == 0 {
		panic("no return value specified for ExportCatalog")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, repo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, repo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_ExportCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportCatalog'
type MockHandlerService_ExportCatalog_Call struct {
	*mock.Call
}

// ExportCatalog is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
func (_e *MockHandlerService_Expecter) ExportCatalog(ctx interface{}, repo interface{}) *MockHandlerService_ExportCatalog_Call {
	return &MockHandlerService_ExportCatalog_Call{Call: _e.mock.On("ExportCatalog", ctx, repo)}
}

func (_c *MockHandlerService_ExportCatalog_Call) Run(run func(ctx context.Context, repo string)) *MockHandlerService_ExportCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockHandlerService_ExportCatalog_Call) Return(_a0 []byte, _a1 error) *MockHandlerService_ExportCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_ExportCatalog_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockHandlerService_ExportCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAttachment provides a mock function with given fields: ctx, repo, ref, attachmentFileName, concat
func (_m *MockHandlerService) FetchAttachment(ctx context.Context, repo string, ref model.AttachmentContainerRef, attachmentFileName string, concat bool) ([]byte, error) {
	ret := _m.Called(ctx, repo, ref, attachmentFileName, concat)

	if len(ret) == 0 {
		panic("no return value specified for FetchAttachment")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.AttachmentContainerRef, string, bool) ([]byte, error)); ok {
		return rf(ctx, repo, ref, attachmentFileName, concat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.AttachmentContainerRef, string, bool) []byte); ok {
		r0 = rf(ctx, repo, ref, attachmentFileName, concat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.AttachmentContainerRef, string, bool) error); ok {
		r1 = rf(ctx, repo, ref, attachmentFileName, concat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_FetchAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAttachment'
type MockHandlerService_FetchAttachment_Call struct {
	*mock.Call
}

// FetchAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - ref model.AttachmentContainerRef
//   - attachmentFileName string
//   - concat bool
func (_e *MockHandlerService_Expecter) FetchAttachment(ctx interface{}, repo interface{}, ref interface{}, attachmentFileName interface{}, concat interface{}) *MockHandlerService_FetchAttachment_Call {
	return &MockHandlerService_FetchAttachment_Call{Call: _e.mock.On("FetchAttachment", ctx, repo, ref, attachmentFileName, concat)}
}

func (_c *MockHandlerService_FetchAttachment_Call) Run(run func(ctx context.Context, repo string, ref model.AttachmentContainerRef, attachmentFileName string, concat bool)) *MockHandlerService_FetchAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.AttachmentContainerRef), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *MockHandlerService_FetchAttachment_Call) Return(_a0 []byte, _a1 error) *MockHandlerService_FetchAttachment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_FetchAttachment_Call) RunAndReturn(run func(context.Context, string, model.AttachmentContainerRef, string, bool) ([]byte, error)) *MockHandlerService_FetchAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// FetchLatestThingModel provides a mock function with given fields: ctx, repo, fetchName, restoreId
func (_m *MockHandlerService) FetchLatestThingModel(ctx context.Context, repo string, fetchName string, restoreId bool) ([]byte, error) {
	ret := _m.Called(ctx, repo, fetchName, restoreId)

	if len(ret) == 0 {
		panic("no return value specified for FetchLatestThingModel")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) ([]byte, error)); ok {
		return rf(ctx, repo, fetchName, restoreId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) []byte); ok {
		r0 = rf(ctx, repo, fetchName, restoreId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, repo, fetchName, restoreId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_FetchLatestThingModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchLatestThingModel'
type MockHandlerService_FetchLatestThingModel_Call struct {
	*mock.Call
}

// FetchLatestThingModel is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - fetchName string
//   - restoreId bool
func (_e *MockHandlerService_Expecter) FetchLatestThingModel(ctx interface{}, repo interface{}, fetchName interface{}, restoreId interface{}) *MockHandlerService_FetchLatestThingModel_Call {
	return &MockHandlerService_FetchLatestThingModel_Call{Call: _e.mock.On("FetchLatestThingModel", ctx, repo, fetchName, restoreId)}
}

func (_c *MockHandlerService_FetchLatestThingModel_Call) Run(run func(ctx context.Context, repo string, fetchName string, restoreId bool)) *MockHandlerService_FetchLatestThingModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockHandlerService_FetchLatestThingModel_Call) Return(_a0 []byte, _a1 error) *MockHandlerService_FetchLatestThingModel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_FetchLatestThingModel_Call) RunAndReturn(run func(context.Context, string, string, bool) ([]byte, error)) *MockHandlerService_FetchLatestThingModel_Call {
	_c.Call.Return(run)
	return _c
}

// FetchThingModel provides a mock function with given fields: ctx, repo, tmID, restoreId
func (_m *MockHandlerService) FetchThingModel(ctx context.Context, repo string, tmID string, restoreId bool) ([]byte, error) {
	ret := _m.Called(ctx, repo, tmID, restoreId)

	if len(ret) == 0 {
		panic("no return value specified for FetchThingModel")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) ([]byte, error)); ok {
		return rf(ctx, repo, tmID, restoreId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) []byte); ok {
		r0 = rf(ctx, repo, tmID, restoreId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, repo, tmID, restoreId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_FetchThingModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchThingModel'
type MockHandlerService_FetchThingModel_Call struct {
	*mock.Call
}

// FetchThingModel is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - tmID string
//   - restoreId bool
func (_e *MockHandlerService_Expecter) FetchThingModel(ctx interface{}, repo interface{}, tmID interface{}, restoreId interface{}) *MockHandlerService_FetchThingModel_Call {
	return &MockHandlerService_FetchThingModel_Call{Call: _e.mock.On("FetchThingModel", ctx, repo, tmID, restoreId)}
}

func (_c *MockHandlerService_FetchThingModel_Call) Run(run func(ctx context.Context, repo string, tmID string, restoreId bool)) *MockHandlerService_FetchThingModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockHandlerService_FetchThingModel_Call) Return(_a0 []byte, _a1 error) *MockHandlerService_FetchThingModel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_FetchThingModel_Call) RunAndReturn(run func(context.Context, string, string, bool) ([]byte, error)) *MockHandlerService_FetchThingModel_Call {
	_c.Call.Return(run)
	return _c
}

// FindInventoryEntries provides a mock function with given fields: ctx, repo, name
func (_m *MockHandlerService) FindInventoryEntries(ctx context.Context, repo string, name string) ([]model.FoundEntry, error) {
	ret := _m.Called(ctx, repo, name)

	if len(ret) == 0 {
		panic("no return value specified for FindInventoryEntries")
	}

	var r0 []model.FoundEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.FoundEntry, error)); ok {
		return rf(ctx, repo, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.FoundEntry); ok {
		r0 = rf(ctx, repo, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FoundEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, repo, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_FindInventoryEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindInventoryEntries'
type MockHandlerService_FindInventoryEntries_Call struct {
	*mock.Call
}

// FindInventoryEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - name string
func (_e *MockHandlerService_Expecter) FindInventoryEntries(ctx interface{}, repo interface{}, name interface{}) *MockHandlerService_FindInventoryEntries_Call {
	return &MockHandlerService_FindInventoryEntries_Call{Call: _e.mock.On("FindInventoryEntries", ctx, repo, name)}
}

func (_c *MockHandlerService_FindInventoryEntries_Call) Run(run func(ctx context.Context, repo string, name string)) *MockHandlerService_FindInventoryEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockHandlerService_FindInventoryEntries_Call) Return(_a0 []model.FoundEntry, _a1 error) *MockHandlerService_FindInventoryEntries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_FindInventoryEntries_Call) RunAndReturn(run func(context.Context, string, string) ([]model.FoundEntry, error)) *MockHandlerService_FindInventoryEntries_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompletions provides a mock function with given fields: ctx, kind, args, toComplete
func (_m *MockHandlerService) GetCompletions(ctx context.Context, kind string, args []string, toComplete string) ([]string, error) {
	ret := _m.Called(ctx, kind, args, toComplete)

	if len(ret) == 0 {
		panic("no return value specified for GetCompletions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, string) ([]string, error)); ok {
		return rf(ctx, kind, args, toComplete)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, string) []string); ok {
		r0 = rf(ctx, kind, args, toComplete)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, string) error); ok {
		r1 = rf(ctx, kind, args, toComplete)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_GetCompletions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompletions'
type MockHandlerService_GetCompletions_Call struct {
	*mock.Call
}

// GetCompletions is a helper method to define mock.On call
//   - ctx context.Context
//   - kind string
//   - args []string
//   - toComplete string
func (_e *MockHandlerService_Expecter) GetCompletions(ctx interface{}, kind interface{}, args interface{}, toComplete interface{}) *MockHandlerService_GetCompletions_Call {
	return &MockHandlerService_GetCompletions_Call{Call: _e.mock.On("GetCompletions", ctx, kind, args, toComplete)}
}

func (_c *MockHandlerService_GetCompletions_Call) Run(run func(ctx context.Context, kind string, args []string, toComplete string)) *MockHandlerService_GetCompletions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(string))
	})
	return _c
}

func (_c *MockHandlerService_GetCompletions_Call) Return(_a0 []string, _a1 error) *MockHandlerService_GetCompletions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_GetCompletions_Call) RunAndReturn(run func(context.Context, string, []string, string) ([]string, error)) *MockHandlerService_GetCompletions_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestTMMetadata provides a mock function with given fields: ctx, repo, fetchName
func (_m *MockHandlerService) GetLatestTMMetadata(ctx context.Context, repo string, fetchName string) (model.FoundVersion, error) {
	ret := _m.Called(ctx, repo, fetchName)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestTMMetadata")
	}

	var r0 model.FoundVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.FoundVersion, error)); ok {
		return rf(ctx, repo, fetchName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.FoundVersion); ok {
		r0 = rf(ctx, repo, fetchName)
	} else {
		r0 = ret.Get(0).(model.FoundVersion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, repo, fetchName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_GetLatestTMMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestTMMetadata'
type MockHandlerService_GetLatestTMMetadata_Call struct {
	*mock.Call
}

// GetLatestTMMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - fetchName string
func (_e *MockHandlerService_Expecter) GetLatestTMMetadata(ctx interface{}, repo interface{}, fetchName interface{}) *MockHandlerService_GetLatestTMMetadata_Call {
	return &MockHandlerService_GetLatestTMMetadata_Call{Call: _e.mock.On("GetLatestTMMetadata", ctx, repo, fetchName)}
}

func (_c *MockHandlerService_GetLatestTMMetadata_Call) Run(run func(ctx context.Context, repo string, fetchName string)) *MockHandlerService_GetLatestTMMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockHandlerService_GetLatestTMMetadata_Call) Return(_a0 model.FoundVersion, _a1 error) *MockHandlerService_GetLatestTMMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_GetLatestTMMetadata_Call) RunAndReturn(run func(context.Context, string, string) (model.FoundVersion, error)) *MockHandlerService_GetLatestTMMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetTMMetadata provides a mock function with given fields: ctx, repo, tmID
func (_m *MockHandlerService) GetTMMetadata(ctx context.Context, repo string, tmID string) ([]model.FoundVersion, error) {
	ret := _m.Called(ctx, repo, tmID)

	if len(ret) == 0 {
		panic("no return value specified for GetTMMetadata")
	}

	var r0 []model.FoundVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.FoundVersion, error)); ok {
		return rf(ctx, repo, tmID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.FoundVersion); ok {
		r0 = rf(ctx, repo, tmID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FoundVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, repo, tmID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_GetTMMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTMMetadata'
type MockHandlerService_GetTMMetadata_Call struct {
	*mock.Call
}

// GetTMMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - tmID string
func (_e *MockHandlerService_Expecter) GetTMMetadata(ctx interface{}, repo interface{}, tmID interface{}) *MockHandlerService_GetTMMetadata_Call {
	return &MockHandlerService_GetTMMetadata_Call{Call: _e.mock.On("GetTMMetadata", ctx, repo, tmID)}
}

func (_c *MockHandlerService_GetTMMetadata_Call) Run(run func(ctx context.Context, repo string, tmID string)) *MockHandlerService_GetTMMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockHandlerService_GetTMMetadata_Call) Return(_a0 []model.FoundVersion, _a1 error) *MockHandlerService_GetTMMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_GetTMMetadata_Call) RunAndReturn(run func(context.Context, string, string) ([]model.FoundVersion, error)) *MockHandlerService_GetTMMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// ImportAttachment provides a mock function with given fields: ctx, repo, ref, attachmentFileName, content, contentType, force
func (_m *MockHandlerService) ImportAttachment(ctx context.Context, repo string, ref model.AttachmentContainerRef, attachmentFileName string, content []byte, contentType string, force bool) error {
	ret := _m.Called(ctx, repo, ref, attachmentFileName, content, contentType, force)

	if len(ret) == 0 {
		panic("no return value specified for ImportAttachment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.AttachmentContainerRef, string, []byte, string, bool) error); ok {
		r0 = rf(ctx, repo, ref, attachmentFileName, content, contentType, force)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandlerService_ImportAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportAttachment'
type MockHandlerService_ImportAttachment_Call struct {
	*mock.Call
}

// ImportAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - ref model.AttachmentContainerRef
//   - attachmentFileName string
//   - content []byte
//   - contentType string
//   - force bool
func (_e *MockHandlerService_Expecter) ImportAttachment(ctx interface{}, repo interface{}, ref interface{}, attachmentFileName interface{}, content interface{}, contentType interface{}, force interface{}) *MockHandlerService_ImportAttachment_Call {
	return &MockHandlerService_ImportAttachment_Call{Call: _e.mock.On("ImportAttachment", ctx, repo, ref, attachmentFileName, content, contentType, force)}
}

func (_c *MockHandlerService_ImportAttachment_Call) Run(run func(ctx context.Context, repo string, ref model.AttachmentContainerRef, attachmentFileName string, content []byte, contentType string, force bool)) *MockHandlerService_ImportAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.AttachmentContainerRef), args[3].(string), args[4].([]byte), args[5].(string), args[6].(bool))
	})
	return _c
}

func (_c *MockHandlerService_ImportAttachment_Call) Return(_a0 error) *MockHandlerService_ImportAttachment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerService_ImportAttachment_Call) RunAndReturn(run func(context.Context, string, model.AttachmentContainerRef, string, []byte, string, bool) error) *MockHandlerService_ImportAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// ImportThingModel provides a mock function with given fields: ctx, repo, file, opts
func (_m *MockHandlerService) ImportThingModel(ctx context.Context, repo string, file []byte, opts repos.ImportOptions) (repos.ImportResult, error) {
	ret := _m.Called(ctx, repo, file, opts)

	if len(ret) == 0 {
		panic("no return value specified for ImportThingModel")
	}

	var r0 repos.ImportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, repos.ImportOptions) (repos.ImportResult, error)); ok {
		return rf(ctx, repo, file, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, repos.ImportOptions) repos.ImportResult); ok {
		r0 = rf(ctx, repo, file, opts)
	} else {
		r0 = ret.Get(0).(repos.ImportResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, repos.ImportOptions) error); ok {
		r1 = rf(ctx, repo, file, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_ImportThingModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportThingModel'
type MockHandlerService_ImportThingModel_Call struct {
	*mock.Call
}

// ImportThingModel is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - file []byte
//   - opts repos.ImportOptions
func (_e *MockHandlerService_Expecter) ImportThingModel(ctx interface{}, repo interface{}, file interface{}, opts interface{}) *MockHandlerService_ImportThingModel_Call {
	return &MockHandlerService_ImportThingModel_Call{Call: _e.mock.On("ImportThingModel", ctx, repo, file, opts)}
}

func (_c *MockHandlerService_ImportThingModel_Call) Run(run func(ctx context.Context, repo string, file []byte, opts repos.ImportOptions)) *MockHandlerService_ImportThingModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(repos.ImportOptions))
	})
	return _c
}

func (_c *MockHandlerService_ImportThingModel_Call) Return(_a0 repos.ImportResult, _a1 error) *MockHandlerService_ImportThingModel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_ImportThingModel_Call) RunAndReturn(run func(context.Context, string, []byte, repos.ImportOptions) (repos.ImportResult, error)) *MockHandlerService_ImportThingModel_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuthors provides a mock function with given fields: ctx, filters
func (_m *MockHandlerService) ListAuthors(ctx context.Context, filters *model.Filters) ([]string, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListAuthors")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) ([]string, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) []string); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Filters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_ListAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuthors'
type MockHandlerService_ListAuthors_Call struct {
	*mock.Call
}

// ListAuthors is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *model.Filters
func (_e *MockHandlerService_Expecter) ListAuthors(ctx interface{}, filters interface{}) *MockHandlerService_ListAuthors_Call {
	return &MockHandlerService_ListAuthors_Call{Call: _e.mock.On("ListAuthors", ctx, filters)}
}

func (_c *MockHandlerService_ListAuthors_Call) Run(run func(ctx context.Context, filters *model.Filters)) *MockHandlerService_ListAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Filters))
	})
	return _c
}

func (_c *MockHandlerService_ListAuthors_Call) Return(_a0 []string, _a1 error) *MockHandlerService_ListAuthors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_ListAuthors_Call) RunAndReturn(run func(context.Context, *model.Filters) ([]string, error)) *MockHandlerService_ListAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// ListInventory provides a mock function with given fields: ctx, repo, filters, offset, limit
func (_m *MockHandlerService) ListInventory(ctx context.Context, repo string, filters *model.Filters, offset int, limit int) (*model.SearchResult, error) {
	ret := _m.Called(ctx, repo, filters, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListInventory")
	}

	var r0 *model.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.Filters, int, int) (*model.SearchResult, error)); ok {
		return rf(ctx, repo, filters, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.Filters, int, int) *model.SearchResult); ok {
		r0 = rf(ctx, repo, filters, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.Filters, int, int) error); ok {
		r1 = rf(ctx, repo, filters, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_ListInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInventory'
type MockHandlerService_ListInventory_Call struct {
	*mock.Call
}

// ListInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - filters *model.Filters
//   - offset int
//   - limit int
func (_e *MockHandlerService_Expecter) ListInventory(ctx interface{}, repo interface{}, filters interface{}, offset interface{}, limit interface{}) *MockHandlerService_ListInventory_Call {
	return &MockHandlerService_ListInventory_Call{Call: _e.mock.On("ListInventory", ctx, repo, filters, offset, limit)}
}

func (_c *MockHandlerService_ListInventory_Call) Run(run func(ctx context.Context, repo string, filters *model.Filters, offset int, limit int)) *MockHandlerService_ListInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.Filters), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockHandlerService_ListInventory_Call) Return(_a0 *model.SearchResult, _a1 error) *MockHandlerService_ListInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_ListInventory_Call) RunAndReturn(run func(context.Context, string, *model.Filters, int, int) (*model.SearchResult, error)) *MockHandlerService_ListInventory_Call {
	_c.Call.Return(run)
	return _c
}

// ListManufacturers provides a mock function with given fields: ctx, filters
func (_m *MockHandlerService) ListManufacturers(ctx context.Context, filters *model.Filters) ([]string, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListManufacturers")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) ([]string, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) []string); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Filters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_ListManufacturers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListManufacturers'
type MockHandlerService_ListManufacturers_Call struct {
	*mock.Call
}

// ListManufacturers is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *model.Filters
func (_e *MockHandlerService_Expecter) ListManufacturers(ctx interface{}, filters interface{}) *MockHandlerService_ListManufacturers_Call {
	return &MockHandlerService_ListManufacturers_Call{Call: _e.mock.On("ListManufacturers", ctx, filters)}
}

func (_c *MockHandlerService_ListManufacturers_Call) Run(run func(ctx context.Context, filters *model.Filters)) *MockHandlerService_ListManufacturers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Filters))
	})
	return _c
}

func (_c *MockHandlerService_ListManufacturers_Call) Return(_a0 []string, _a1 error) *MockHandlerService_ListManufacturers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_ListManufacturers_Call) RunAndReturn(run func(context.Context, *model.Filters) ([]string, error)) *MockHandlerService_ListManufacturers_Call {
	_c.Call.Return(run)
	return _c
}

// ListMpns provides a mock function with given fields: ctx, filters
func (_m *MockHandlerService) ListMpns(ctx context.Context, filters *model.Filters) ([]string, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListMpns")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) ([]string, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) []string); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Filters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_ListMpns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMpns'
type MockHandlerService_ListMpns_Call struct {
	*mock.Call
}

// ListMpns is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *model.Filters
func (_e *MockHandlerService_Expecter) ListMpns(ctx interface{}, filters interface{}) *MockHandlerService_ListMpns_Call {
	return &MockHandlerService_ListMpns_Call{Call: _e.mock.On("ListMpns", ctx, filters)}
}

func (_c *MockHandlerService_ListMpns_Call) Run(run func(ctx context.Context, filters *model.Filters)) *MockHandlerService_ListMpns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Filters))
	})
	return _c
}

func (_c *MockHandlerService_ListMpns_Call) Return(_a0 []string, _a1 error) *MockHandlerService_ListMpns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_ListMpns_Call) RunAndReturn(run func(context.Context, *model.Filters) ([]string, error)) *MockHandlerService_ListMpns_Call {
	_c.Call.Return(run)
	return _c
}

// ListRepos provides a mock function with given fields: ctx
func (_m *MockHandlerService) ListRepos(ctx context.Context) ([]model.RepoDescription, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRepos")
	}

	var r0 []model.RepoDescription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.RepoDescription, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.RepoDescription); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RepoDescription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_ListRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRepos'
type MockHandlerService_ListRepos_Call struct {
	*mock.Call
}

// ListRepos is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHandlerService_Expecter) ListRepos(ctx interface{}) *MockHandlerService_ListRepos_Call {
	return &MockHandlerService_ListRepos_Call{Call: _e.mock.On("ListRepos", ctx)}
}

func (_c *MockHandlerService_ListRepos_Call) Run(run func(ctx context.Context)) *MockHandlerService_ListRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHandlerService_ListRepos_Call) Return(_a0 []model.RepoDescription, _a1 error) *MockHandlerService_ListRepos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_ListRepos_Call) RunAndReturn(run func(context.Context) ([]model.RepoDescription, error)) *MockHandlerService_ListRepos_Call {
	_c.Call.Return(run)
	return _c
}

// SearchInventory provides a mock function with given fields: ctx, repo, query, offset, limit
func (_m *MockHandlerService) SearchInventory(ctx context.Context, repo string, query string, offset int, limit int) (*model.SearchResult, error) {
	ret := _m.Called(ctx, repo, query, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchInventory")
	}

	var r0 *model.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) (*model.SearchResult, error)); ok {
		return rf(ctx, repo, query, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) *model.SearchResult); ok {
		r0 = rf(ctx, repo, query, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = rf(ctx, repo, query, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandlerService_SearchInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchInventory'
type MockHandlerService_SearchInventory_Call struct {
	*mock.Call
}

// SearchInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - query string
//   - offset int
//   - limit int
func (_e *MockHandlerService_Expecter) SearchInventory(ctx interface{}, repo interface{}, query interface{}, offset interface{}, limit interface{}) *MockHandlerService_SearchInventory_Call {
	return &MockHandlerService_SearchInventory_Call{Call: _e.mock.On("SearchInventory", ctx, repo, query, offset, limit)}
}

func (_c *MockHandlerService_SearchInventory_Call) Run(run func(ctx context.Context, repo string, query string, offset int, limit int)) *MockHandlerService_SearchInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockHandlerService_SearchInventory_Call) Return(_a0 *model.SearchResult, _a1 error) *MockHandlerService_SearchInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandlerService_SearchInventory_Call) RunAndReturn(run func(context.Context, string, string, int, int) (*model.SearchResult, error)) *MockHandlerService_SearchInventory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHandlerService creates a new instance of MockHandlerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandlerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandlerService {
	mock := &MockHandlerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
