// Code generated by mockery v2.39.1. DO NOT EDIT.

package remotes

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/web-of-things-open-source/tm-catalog-cli/internal/model"
)

// MockRemote is an autogenerated mock type for the Remote type
type MockRemote struct {
	mock.Mock
}

// CreateToC provides a mock function with given fields:
func (_m *MockRemote) CreateToC() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateToC")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: id
func (_m *MockRemote) Fetch(id string) (string, []byte, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 string
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, []byte, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) []byte); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// List provides a mock function with given fields: search
func (_m *MockRemote) List(search *model.SearchParams) (model.SearchResult, error) {
	ret := _m.Called(search)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 model.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.SearchParams) (model.SearchResult, error)); ok {
		return rf(search)
	}
	if rf, ok := ret.Get(0).(func(*model.SearchParams) model.SearchResult); ok {
		r0 = rf(search)
	} else {
		r0 = ret.Get(0).(model.SearchResult)
	}

	if rf, ok := ret.Get(1).(func(*model.SearchParams) error); ok {
		r1 = rf(search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Name provides a mock function with given fields:
func (_m *MockRemote) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Push provides a mock function with given fields: id, raw
func (_m *MockRemote) Push(id model.TMID, raw []byte) error {
	ret := _m.Called(id, raw)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TMID, []byte) error); ok {
		r0 = rf(id, raw)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Versions provides a mock function with given fields: name
func (_m *MockRemote) Versions(name string) (model.FoundEntry, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Versions")
	}

	var r0 model.FoundEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (model.FoundEntry, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) model.FoundEntry); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(model.FoundEntry)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRemote creates a new instance of MockRemote. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemote(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemote {
	mock := &MockRemote{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
