// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	commands "github.com/wot-oss/tmc/internal/commands"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wot-oss/tmc/internal/model"
	repos "github.com/wot-oss/tmc/internal/repos"
)

// HandlerService is an autogenerated mock type for the HandlerService type
type HandlerService struct {
	mock.Mock
}

type HandlerService_Expecter struct {
	mock *mock.Mock
}

func (_m *HandlerService) EXPECT() *HandlerService_Expecter {
	return &HandlerService_Expecter{mock: &_m.Mock}
}

// AddThingModelVariant provides a mock function with given fields: ctx, repo, tmID, opts
func (_m *HandlerService) AddThingModelVariant(ctx context.Context, repo string, tmID string, opts commands.AddVariantOptions) error {
	ret := _m.Called(ctx, repo, tmID, opts)

	if len(ret) == 0 {
		panic("no return value specified for AddThingModelVariant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, commands.AddVariantOptions) error); ok {
		r0 = rf(ctx, repo, tmID, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandlerService_AddThingModelVariant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddThingModelVariant'
type HandlerService_AddThingModelVariant_Call struct {
	*mock.Call
}

// AddThingModelVariant is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - tmID string
//   - opts commands.AddVariantOptions
func (_e *HandlerService_Expecter) AddThingModelVariant(ctx interface{}, repo interface{}, tmID interface{}, opts interface{}) *HandlerService_AddThingModelVariant_Call {
	return &HandlerService_AddThingModelVariant_Call{Call: _e.mock.On("AddThingModelVariant", ctx, repo, tmID, opts)}
}

func (_c *HandlerService_AddThingModelVariant_Call) Run(run func(ctx context.Context, repo string, tmID string, opts commands.AddVariantOptions)) *HandlerService_AddThingModelVariant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(commands.AddVariantOptions))
	})
	return _c
}

func (_c *HandlerService_AddThingModelVariant_Call) Return(_a0 error) *HandlerService_AddThingModelVariant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HandlerService_AddThingModelVariant_Call) RunAndReturn(run func(context.Context, string, string, commands.AddVariantOptions) error) *HandlerService_AddThingModelVariant_Call {
	_c.Call.Return(run)
	return _c
}

// AddThingModelVariantBatch provides a mock function with given fields: ctx, repo, familyTMID, requests
func (_m *HandlerService) AddThingModelVariantBatch(ctx context.Context, repo string, familyTMID string, requests []commands.AddVariantBatchRequest) []commands.AddVariantBatchResult {
	ret := _m.Called(ctx, repo, familyTMID, requests)

	if len(ret) == 0 {
		panic("no return value specified for AddThingModelVariantBatch")
	}

	var r0 []commands.AddVariantBatchResult
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []commands.AddVariantBatchRequest) []commands.AddVariantBatchResult); ok {
		r0 = rf(ctx, repo, familyTMID, requests)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]commands.AddVariantBatchResult)
		}
	}

	return r0
}

// HandlerService_AddThingModelVariantBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddThingModelVariantBatch'
type HandlerService_AddThingModelVariantBatch_Call struct {
	*mock.Call
}

// AddThingModelVariantBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - familyTMID string
//   - requests []commands.AddVariantBatchRequest
func (_e *HandlerService_Expecter) AddThingModelVariantBatch(ctx interface{}, repo interface{}, familyTMID interface{}, requests interface{}) *HandlerService_AddThingModelVariantBatch_Call {
	return &HandlerService_AddThingModelVariantBatch_Call{Call: _e.mock.On("AddThingModelVariantBatch", ctx, repo, familyTMID, requests)}
}

func (_c *HandlerService_AddThingModelVariantBatch_Call) Run(run func(ctx context.Context, repo string, familyTMID string, requests []commands.AddVariantBatchRequest)) *HandlerService_AddThingModelVariantBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]commands.AddVariantBatchRequest))
	})
	return _c
}

func (_c *HandlerService_AddThingModelVariantBatch_Call) Return(_a0 []commands.AddVariantBatchResult) *HandlerService_AddThingModelVariantBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HandlerService_AddThingModelVariantBatch_Call) RunAndReturn(run func(context.Context, string, string, []commands.AddVariantBatchRequest) []commands.AddVariantBatchResult) *HandlerService_AddThingModelVariantBatch_Call {
	_c.Call.Return(run)
	return _c
}

// CheckHealth provides a mock function with given fields: ctx
func (_m *HandlerService) CheckHealth(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandlerService_CheckHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHealth'
type HandlerService_CheckHealth_Call struct {
	*mock.Call
}

// CheckHealth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HandlerService_Expecter) CheckHealth(ctx interface{}) *HandlerService_CheckHealth_Call {
	return &HandlerService_CheckHealth_Call{Call: _e.mock.On("CheckHealth", ctx)}
}

func (_c *HandlerService_CheckHealth_Call) Run(run func(ctx context.Context)) *HandlerService_CheckHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HandlerService_CheckHealth_Call) Return(_a0 error) *HandlerService_CheckHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HandlerService_CheckHealth_Call) RunAndReturn(run func(context.Context) error) *HandlerService_CheckHealth_Call {
	_c.Call.Return(run)
	return _c
}

// CheckHealthLive provides a mock function with given fields: ctx
func (_m *HandlerService) CheckHealthLive(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealthLive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandlerService_CheckHealthLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHealthLive'
type HandlerService_CheckHealthLive_Call struct {
	*mock.Call
}

// CheckHealthLive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HandlerService_Expecter) CheckHealthLive(ctx interface{}) *HandlerService_CheckHealthLive_Call {
	return &HandlerService_CheckHealthLive_Call{Call: _e.mock.On("CheckHealthLive", ctx)}
}

func (_c *HandlerService_CheckHealthLive_Call) Run(run func(ctx context.Context)) *HandlerService_CheckHealthLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HandlerService_CheckHealthLive_Call) Return(_a0 error) *HandlerService_CheckHealthLive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HandlerService_CheckHealthLive_Call) RunAndReturn(run func(context.Context) error) *HandlerService_CheckHealthLive_Call {
	_c.Call.Return(run)
	return _c
}

// CheckHealthReady provides a mock function with given fields: ctx
func (_m *HandlerService) CheckHealthReady(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealthReady")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandlerService_CheckHealthReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHealthReady'
type HandlerService_CheckHealthReady_Call struct {
	*mock.Call
}

// CheckHealthReady is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HandlerService_Expecter) CheckHealthReady(ctx interface{}) *HandlerService_CheckHealthReady_Call {
	return &HandlerService_CheckHealthReady_Call{Call: _e.mock.On("CheckHealthReady", ctx)}
}

func (_c *HandlerService_CheckHealthReady_Call) Run(run func(ctx context.Context)) *HandlerService_CheckHealthReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HandlerService_CheckHealthReady_Call) Return(_a0 error) *HandlerService_CheckHealthReady_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HandlerService_CheckHealthReady_Call) RunAndReturn(run func(context.Context) error) *HandlerService_CheckHealthReady_Call {
	_c.Call.Return(run)
	return _c
}

// CheckHealthStartup provides a mock function with given fields: ctx
func (_m *HandlerService) CheckHealthStartup(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealthStartup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandlerService_CheckHealthStartup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHealthStartup'
type HandlerService_CheckHealthStartup_Call struct {
	*mock.Call
}

// CheckHealthStartup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HandlerService_Expecter) CheckHealthStartup(ctx interface{}) *HandlerService_CheckHealthStartup_Call {
	return &HandlerService_CheckHealthStartup_Call{Call: _e.mock.On("CheckHealthStartup", ctx)}
}

func (_c *HandlerService_CheckHealthStartup_Call) Run(run func(ctx context.Context)) *HandlerService_CheckHealthStartup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HandlerService_CheckHealthStartup_Call) Return(_a0 error) *HandlerService_CheckHealthStartup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HandlerService_CheckHealthStartup_Call) RunAndReturn(run func(context.Context) error) *HandlerService_CheckHealthStartup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAttachment provides a mock function with given fields: ctx, repo, ref, attachmentFileName
func (_m *HandlerService) DeleteAttachment(ctx context.Context, repo string, ref model.AttachmentContainerRef, attachmentFileName string) error {
	ret := _m.Called(ctx, repo, ref, attachmentFileName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttachment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.AttachmentContainerRef, string) error); ok {
		r0 = rf(ctx, repo, ref, attachmentFileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandlerService_DeleteAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttachment'
type HandlerService_DeleteAttachment_Call struct {
	*mock.Call
}

// DeleteAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - ref model.AttachmentContainerRef
//   - attachmentFileName string
func (_e *HandlerService_Expecter) DeleteAttachment(ctx interface{}, repo interface{}, ref interface{}, attachmentFileName interface{}) *HandlerService_DeleteAttachment_Call {
	return &HandlerService_DeleteAttachment_Call{Call: _e.mock.On("DeleteAttachment", ctx, repo, ref, attachmentFileName)}
}

func (_c *HandlerService_DeleteAttachment_Call) Run(run func(ctx context.Context, repo string, ref model.AttachmentContainerRef, attachmentFileName string)) *HandlerService_DeleteAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.AttachmentContainerRef), args[3].(string))
	})
	return _c
}

func (_c *HandlerService_DeleteAttachment_Call) Return(_a0 error) *HandlerService_DeleteAttachment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HandlerService_DeleteAttachment_Call) RunAndReturn(run func(context.Context, string, model.AttachmentContainerRef, string) error) *HandlerService_DeleteAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteThingModel provides a mock function with given fields: ctx, repo, tmID
func (_m *HandlerService) DeleteThingModel(ctx context.Context, repo string, tmID string) error {
	ret := _m.Called(ctx, repo, tmID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteThingModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, repo, tmID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandlerService_DeleteThingModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteThingModel'
type HandlerService_DeleteThingModel_Call struct {
	*mock.Call
}

// DeleteThingModel is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - tmID string
func (_e *HandlerService_Expecter) DeleteThingModel(ctx interface{}, repo interface{}, tmID interface{}) *HandlerService_DeleteThingModel_Call {
	return &HandlerService_DeleteThingModel_Call{Call: _e.mock.On("DeleteThingModel", ctx, repo, tmID)}
}

func (_c *HandlerService_DeleteThingModel_Call) Run(run func(ctx context.Context, repo string, tmID string)) *HandlerService_DeleteThingModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *HandlerService_DeleteThingModel_Call) Return(_a0 error) *HandlerService_DeleteThingModel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HandlerService_DeleteThingModel_Call) RunAndReturn(run func(context.Context, string, string) error) *HandlerService_DeleteThingModel_Call {
	_c.Call.Return(run)
	return _c
}

// ExportCatalog provides a mock function with given fields: ctx, repo
func (_m *HandlerService) ExportCatalog(ctx context.Context, repo string) ([]byte, error) {
	ret := _m.Called(ctx, repo)

	if len(ret) == 0 {
		panic("no return value specified for ExportCatalog")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, repo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, repo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_ExportCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportCatalog'
type HandlerService_ExportCatalog_Call struct {
	*mock.Call
}

// ExportCatalog is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
func (_e *HandlerService_Expecter) ExportCatalog(ctx interface{}, repo interface{}) *HandlerService_ExportCatalog_Call {
	return &HandlerService_ExportCatalog_Call{Call: _e.mock.On("ExportCatalog", ctx, repo)}
}

func (_c *HandlerService_ExportCatalog_Call) Run(run func(ctx context.Context, repo string)) *HandlerService_ExportCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *HandlerService_ExportCatalog_Call) Return(_a0 []byte, _a1 error) *HandlerService_ExportCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_ExportCatalog_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *HandlerService_ExportCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAttachment provides a mock function with given fields: ctx, repo, ref, attachmentFileName, concat
func (_m *HandlerService) FetchAttachment(ctx context.Context, repo string, ref model.AttachmentContainerRef, attachmentFileName string, concat bool) ([]byte, error) {
	ret := _m.Called(ctx, repo, ref, attachmentFileName, concat)

	if len(ret) == 0 {
		panic("no return value specified for FetchAttachment")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.AttachmentContainerRef, string, bool) ([]byte, error)); ok {
		return rf(ctx, repo, ref, attachmentFileName, concat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.AttachmentContainerRef, string, bool) []byte); ok {
		r0 = rf(ctx, repo, ref, attachmentFileName, concat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.AttachmentContainerRef, string, bool) error); ok {
		r1 = rf(ctx, repo, ref, attachmentFileName, concat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_FetchAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAttachment'
type HandlerService_FetchAttachment_Call struct {
	*mock.Call
}

// FetchAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - ref model.AttachmentContainerRef
//   - attachmentFileName string
//   - concat bool
func (_e *HandlerService_Expecter) FetchAttachment(ctx interface{}, repo interface{}, ref interface{}, attachmentFileName interface{}, concat interface{}) *HandlerService_FetchAttachment_Call {
	return &HandlerService_FetchAttachment_Call{Call: _e.mock.On("FetchAttachment", ctx, repo, ref, attachmentFileName, concat)}
}

func (_c *HandlerService_FetchAttachment_Call) Run(run func(ctx context.Context, repo string, ref model.AttachmentContainerRef, attachmentFileName string, concat bool)) *HandlerService_FetchAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.AttachmentContainerRef), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *HandlerService_FetchAttachment_Call) Return(_a0 []byte, _a1 error) *HandlerService_FetchAttachment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_FetchAttachment_Call) RunAndReturn(run func(context.Context, string, model.AttachmentContainerRef, string, bool) ([]byte, error)) *HandlerService_FetchAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// FetchLatestThingModel provides a mock function with given fields: ctx, repo, fetchName, restoreId
func (_m *HandlerService) FetchLatestThingModel(ctx context.Context, repo string, fetchName string, restoreId bool) ([]byte, error) {
	ret := _m.Called(ctx, repo, fetchName, restoreId)

	if len(ret) == 0 {
		panic("no return value specified for FetchLatestThingModel")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) ([]byte, error)); ok {
		return rf(ctx, repo, fetchName, restoreId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) []byte); ok {
		r0 = rf(ctx, repo, fetchName, restoreId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, repo, fetchName, restoreId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_FetchLatestThingModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchLatestThingModel'
type HandlerService_FetchLatestThingModel_Call struct {
	*mock.Call
}

// FetchLatestThingModel is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - fetchName string
//   - restoreId bool
func (_e *HandlerService_Expecter) FetchLatestThingModel(ctx interface{}, repo interface{}, fetchName interface{}, restoreId interface{}) *HandlerService_FetchLatestThingModel_Call {
	return &HandlerService_FetchLatestThingModel_Call{Call: _e.mock.On("FetchLatestThingModel", ctx, repo, fetchName, restoreId)}
}

func (_c *HandlerService_FetchLatestThingModel_Call) Run(run func(ctx context.Context, repo string, fetchName string, restoreId bool)) *HandlerService_FetchLatestThingModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *HandlerService_FetchLatestThingModel_Call) Return(_a0 []byte, _a1 error) *HandlerService_FetchLatestThingModel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_FetchLatestThingModel_Call) RunAndReturn(run func(context.Context, string, string, bool) ([]byte, error)) *HandlerService_FetchLatestThingModel_Call {
	_c.Call.Return(run)
	return _c
}

// FetchThingModel provides a mock function with given fields: ctx, repo, tmID, restoreId
func (_m *HandlerService) FetchThingModel(ctx context.Context, repo string, tmID string, restoreId bool) ([]byte, error) {
	ret := _m.Called(ctx, repo, tmID, restoreId)

	if len(ret) == 0 {
		panic("no return value specified for FetchThingModel")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) ([]byte, error)); ok {
		return rf(ctx, repo, tmID, restoreId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) []byte); ok {
		r0 = rf(ctx, repo, tmID, restoreId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, repo, tmID, restoreId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_FetchThingModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchThingModel'
type HandlerService_FetchThingModel_Call struct {
	*mock.Call
}

// FetchThingModel is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - tmID string
//   - restoreId bool
func (_e *HandlerService_Expecter) FetchThingModel(ctx interface{}, repo interface{}, tmID interface{}, restoreId interface{}) *HandlerService_FetchThingModel_Call {
	return &HandlerService_FetchThingModel_Call{Call: _e.mock.On("FetchThingModel", ctx, repo, tmID, restoreId)}
}

func (_c *HandlerService_FetchThingModel_Call) Run(run func(ctx context.Context, repo string, tmID string, restoreId bool)) *HandlerService_FetchThingModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *HandlerService_FetchThingModel_Call) Return(_a0 []byte, _a1 error) *HandlerService_FetchThingModel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_FetchThingModel_Call) RunAndReturn(run func(context.Context, string, string, bool) ([]byte, error)) *HandlerService_FetchThingModel_Call {
	_c.Call.Return(run)
	return _c
}

// FindInventoryEntries provides a mock function with given fields: ctx, repo, name
func (_m *HandlerService) FindInventoryEntries(ctx context.Context, repo string, name string) ([]model.FoundEntry, error) {
	ret := _m.Called(ctx, repo, name)

	if len(ret) == 0 {
		panic("no return value specified for FindInventoryEntries")
	}

	var r0 []model.FoundEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.FoundEntry, error)); ok {
		return rf(ctx, repo, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.FoundEntry); ok {
		r0 = rf(ctx, repo, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FoundEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, repo, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_FindInventoryEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindInventoryEntries'
type HandlerService_FindInventoryEntries_Call struct {
	*mock.Call
}

// FindInventoryEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - name string
func (_e *HandlerService_Expecter) FindInventoryEntries(ctx interface{}, repo interface{}, name interface{}) *HandlerService_FindInventoryEntries_Call {
	return &HandlerService_FindInventoryEntries_Call{Call: _e.mock.On("FindInventoryEntries", ctx, repo, name)}
}

func (_c *HandlerService_FindInventoryEntries_Call) Run(run func(ctx context.Context, repo string, name string)) *HandlerService_FindInventoryEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *HandlerService_FindInventoryEntries_Call) Return(_a0 []model.FoundEntry, _a1 error) *HandlerService_FindInventoryEntries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_FindInventoryEntries_Call) RunAndReturn(run func(context.Context, string, string) ([]model.FoundEntry, error)) *HandlerService_FindInventoryEntries_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompletions provides a mock function with given fields: ctx, kind, args, toComplete
func (_m *HandlerService) GetCompletions(ctx context.Context, kind string, args []string, toComplete string) ([]string, error) {
	ret := _m.Called(ctx, kind, args, toComplete)

	if len(ret) == 0 {
		panic("no return value specified for GetCompletions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, string) ([]string, error)); ok {
		return rf(ctx, kind, args, toComplete)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, string) []string); ok {
		r0 = rf(ctx, kind, args, toComplete)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, string) error); ok {
		r1 = rf(ctx, kind, args, toComplete)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_GetCompletions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompletions'
type HandlerService_GetCompletions_Call struct {
	*mock.Call
}

// GetCompletions is a helper method to define mock.On call
//   - ctx context.Context
//   - kind string
//   - args []string
//   - toComplete string
func (_e *HandlerService_Expecter) GetCompletions(ctx interface{}, kind interface{}, args interface{}, toComplete interface{}) *HandlerService_GetCompletions_Call {
	return &HandlerService_GetCompletions_Call{Call: _e.mock.On("GetCompletions", ctx, kind, args, toComplete)}
}

func (_c *HandlerService_GetCompletions_Call) Run(run func(ctx context.Context, kind string, args []string, toComplete string)) *HandlerService_GetCompletions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(string))
	})
	return _c
}

func (_c *HandlerService_GetCompletions_Call) Return(_a0 []string, _a1 error) *HandlerService_GetCompletions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_GetCompletions_Call) RunAndReturn(run func(context.Context, string, []string, string) ([]string, error)) *HandlerService_GetCompletions_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestTMMetadata provides a mock function with given fields: ctx, repo, fetchName
func (_m *HandlerService) GetLatestTMMetadata(ctx context.Context, repo string, fetchName string) (model.FoundVersion, error) {
	ret := _m.Called(ctx, repo, fetchName)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestTMMetadata")
	}

	var r0 model.FoundVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.FoundVersion, error)); ok {
		return rf(ctx, repo, fetchName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.FoundVersion); ok {
		r0 = rf(ctx, repo, fetchName)
	} else {
		r0 = ret.Get(0).(model.FoundVersion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, repo, fetchName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_GetLatestTMMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestTMMetadata'
type HandlerService_GetLatestTMMetadata_Call struct {
	*mock.Call
}

// GetLatestTMMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - fetchName string
func (_e *HandlerService_Expecter) GetLatestTMMetadata(ctx interface{}, repo interface{}, fetchName interface{}) *HandlerService_GetLatestTMMetadata_Call {
	return &HandlerService_GetLatestTMMetadata_Call{Call: _e.mock.On("GetLatestTMMetadata", ctx, repo, fetchName)}
}

func (_c *HandlerService_GetLatestTMMetadata_Call) Run(run func(ctx context.Context, repo string, fetchName string)) *HandlerService_GetLatestTMMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *HandlerService_GetLatestTMMetadata_Call) Return(_a0 model.FoundVersion, _a1 error) *HandlerService_GetLatestTMMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_GetLatestTMMetadata_Call) RunAndReturn(run func(context.Context, string, string) (model.FoundVersion, error)) *HandlerService_GetLatestTMMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetTMMetadata provides a mock function with given fields: ctx, repo, tmID
func (_m *HandlerService) GetTMMetadata(ctx context.Context, repo string, tmID string) ([]model.FoundVersion, error) {
	ret := _m.Called(ctx, repo, tmID)

	if len(ret) == 0 {
		panic("no return value specified for GetTMMetadata")
	}

	var r0 []model.FoundVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.FoundVersion, error)); ok {
		return rf(ctx, repo, tmID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.FoundVersion); ok {
		r0 = rf(ctx, repo, tmID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FoundVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, repo, tmID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_GetTMMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTMMetadata'
type HandlerService_GetTMMetadata_Call struct {
	*mock.Call
}

// GetTMMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - tmID string
func (_e *HandlerService_Expecter) GetTMMetadata(ctx interface{}, repo interface{}, tmID interface{}) *HandlerService_GetTMMetadata_Call {
	return &HandlerService_GetTMMetadata_Call{Call: _e.mock.On("GetTMMetadata", ctx, repo, tmID)}
}

func (_c *HandlerService_GetTMMetadata_Call) Run(run func(ctx context.Context, repo string, tmID string)) *HandlerService_GetTMMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *HandlerService_GetTMMetadata_Call) Return(_a0 []model.FoundVersion, _a1 error) *HandlerService_GetTMMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_GetTMMetadata_Call) RunAndReturn(run func(context.Context, string, string) ([]model.FoundVersion, error)) *HandlerService_GetTMMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// ImportAttachment provides a mock function with given fields: ctx, repo, ref, attachmentFileName, content, contentType, force
func (_m *HandlerService) ImportAttachment(ctx context.Context, repo string, ref model.AttachmentContainerRef, attachmentFileName string, content []byte, contentType string, force bool) error {
	ret := _m.Called(ctx, repo, ref, attachmentFileName, content, contentType, force)

	if len(ret) == 0 {
		panic("no return value specified for ImportAttachment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.AttachmentContainerRef, string, []byte, string, bool) error); ok {
		r0 = rf(ctx, repo, ref, attachmentFileName, content, contentType, force)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandlerService_ImportAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportAttachment'
type HandlerService_ImportAttachment_Call struct {
	*mock.Call
}

// ImportAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - ref model.AttachmentContainerRef
//   - attachmentFileName string
//   - content []byte
//   - contentType string
//   - force bool
func (_e *HandlerService_Expecter) ImportAttachment(ctx interface{}, repo interface{}, ref interface{}, attachmentFileName interface{}, content interface{}, contentType interface{}, force interface{}) *HandlerService_ImportAttachment_Call {
	return &HandlerService_ImportAttachment_Call{Call: _e.mock.On("ImportAttachment", ctx, repo, ref, attachmentFileName, content, contentType, force)}
}

func (_c *HandlerService_ImportAttachment_Call) Run(run func(ctx context.Context, repo string, ref model.AttachmentContainerRef, attachmentFileName string, content []byte, contentType string, force bool)) *HandlerService_ImportAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.AttachmentContainerRef), args[3].(string), args[4].([]byte), args[5].(string), args[6].(bool))
	})
	return _c
}

func (_c *HandlerService_ImportAttachment_Call) Return(_a0 error) *HandlerService_ImportAttachment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HandlerService_ImportAttachment_Call) RunAndReturn(run func(context.Context, string, model.AttachmentContainerRef, string, []byte, string, bool) error) *HandlerService_ImportAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// ImportThingModel provides a mock function with given fields: ctx, repo, file, opts
func (_m *HandlerService) ImportThingModel(ctx context.Context, repo string, file []byte, opts repos.ImportOptions) (repos.ImportResult, error) {
	ret := _m.Called(ctx, repo, file, opts)

	if len(ret) == 0 {
		panic("no return value specified for ImportThingModel")
	}

	var r0 repos.ImportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, repos.ImportOptions) (repos.ImportResult, error)); ok {
		return rf(ctx, repo, file, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, repos.ImportOptions) repos.ImportResult); ok {
		r0 = rf(ctx, repo, file, opts)
	} else {
		r0 = ret.Get(0).(repos.ImportResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, repos.ImportOptions) error); ok {
		r1 = rf(ctx, repo, file, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_ImportThingModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportThingModel'
type HandlerService_ImportThingModel_Call struct {
	*mock.Call
}

// ImportThingModel is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - file []byte
//   - opts repos.ImportOptions
func (_e *HandlerService_Expecter) ImportThingModel(ctx interface{}, repo interface{}, file interface{}, opts interface{}) *HandlerService_ImportThingModel_Call {
	return &HandlerService_ImportThingModel_Call{Call: _e.mock.On("ImportThingModel", ctx, repo, file, opts)}
}

func (_c *HandlerService_ImportThingModel_Call) Run(run func(ctx context.Context, repo string, file []byte, opts repos.ImportOptions)) *HandlerService_ImportThingModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(repos.ImportOptions))
	})
	return _c
}

func (_c *HandlerService_ImportThingModel_Call) Return(_a0 repos.ImportResult, _a1 error) *HandlerService_ImportThingModel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_ImportThingModel_Call) RunAndReturn(run func(context.Context, string, []byte, repos.ImportOptions) (repos.ImportResult, error)) *HandlerService_ImportThingModel_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuthors provides a mock function with given fields: ctx, filters
func (_m *HandlerService) ListAuthors(ctx context.Context, filters *model.Filters) ([]string, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListAuthors")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) ([]string, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) []string); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Filters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_ListAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuthors'
type HandlerService_ListAuthors_Call struct {
	*mock.Call
}

// ListAuthors is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *model.Filters
func (_e *HandlerService_Expecter) ListAuthors(ctx interface{}, filters interface{}) *HandlerService_ListAuthors_Call {
	return &HandlerService_ListAuthors_Call{Call: _e.mock.On("ListAuthors", ctx, filters)}
}

func (_c *HandlerService_ListAuthors_Call) Run(run func(ctx context.Context, filters *model.Filters)) *HandlerService_ListAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Filters))
	})
	return _c
}

func (_c *HandlerService_ListAuthors_Call) Return(_a0 []string, _a1 error) *HandlerService_ListAuthors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_ListAuthors_Call) RunAndReturn(run func(context.Context, *model.Filters) ([]string, error)) *HandlerService_ListAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuthorsAttachments provides a mock function with given fields: ctx, repo, authorName
func (_m *HandlerService) ListAuthorsAttachments(ctx context.Context, repo string, authorName string) ([]model.FoundAttachment, error) {
	ret := _m.Called(ctx, repo, authorName)

	if len(ret) == 0 {
		panic("no return value specified for ListAuthorsAttachments")
	}

	var r0 []model.FoundAttachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.FoundAttachment, error)); ok {
		return rf(ctx, repo, authorName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.FoundAttachment); ok {
		r0 = rf(ctx, repo, authorName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FoundAttachment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, repo, authorName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_ListAuthorsAttachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuthorsAttachments'
type HandlerService_ListAuthorsAttachments_Call struct {
	*mock.Call
}

// ListAuthorsAttachments is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - authorName string
func (_e *HandlerService_Expecter) ListAuthorsAttachments(ctx interface{}, repo interface{}, authorName interface{}) *HandlerService_ListAuthorsAttachments_Call {
	return &HandlerService_ListAuthorsAttachments_Call{Call: _e.mock.On("ListAuthorsAttachments", ctx, repo, authorName)}
}

func (_c *HandlerService_ListAuthorsAttachments_Call) Run(run func(ctx context.Context, repo string, authorName string)) *HandlerService_ListAuthorsAttachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *HandlerService_ListAuthorsAttachments_Call) Return(_a0 []model.FoundAttachment, _a1 error) *HandlerService_ListAuthorsAttachments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_ListAuthorsAttachments_Call) RunAndReturn(run func(context.Context, string, string) ([]model.FoundAttachment, error)) *HandlerService_ListAuthorsAttachments_Call {
	_c.Call.Return(run)
	return _c
}

// ListInventory provides a mock function with given fields: ctx, repo, filters, offset, limit
func (_m *HandlerService) ListInventory(ctx context.Context, repo string, filters *model.Filters, offset int, limit int) (*model.SearchResult, error) {
	ret := _m.Called(ctx, repo, filters, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListInventory")
	}

	var r0 *model.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.Filters, int, int) (*model.SearchResult, error)); ok {
		return rf(ctx, repo, filters, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.Filters, int, int) *model.SearchResult); ok {
		r0 = rf(ctx, repo, filters, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.Filters, int, int) error); ok {
		r1 = rf(ctx, repo, filters, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_ListInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInventory'
type HandlerService_ListInventory_Call struct {
	*mock.Call
}

// ListInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - filters *model.Filters
//   - offset int
//   - limit int
func (_e *HandlerService_Expecter) ListInventory(ctx interface{}, repo interface{}, filters interface{}, offset interface{}, limit interface{}) *HandlerService_ListInventory_Call {
	return &HandlerService_ListInventory_Call{Call: _e.mock.On("ListInventory", ctx, repo, filters, offset, limit)}
}

func (_c *HandlerService_ListInventory_Call) Run(run func(ctx context.Context, repo string, filters *model.Filters, offset int, limit int)) *HandlerService_ListInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.Filters), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *HandlerService_ListInventory_Call) Return(_a0 *model.SearchResult, _a1 error) *HandlerService_ListInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_ListInventory_Call) RunAndReturn(run func(context.Context, string, *model.Filters, int, int) (*model.SearchResult, error)) *HandlerService_ListInventory_Call {
	_c.Call.Return(run)
	return _c
}

// ListManufacturers provides a mock function with given fields: ctx, filters
func (_m *HandlerService) ListManufacturers(ctx context.Context, filters *model.Filters) ([]string, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListManufacturers")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) ([]string, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) []string); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Filters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_ListManufacturers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListManufacturers'
type HandlerService_ListManufacturers_Call struct {
	*mock.Call
}

// ListManufacturers is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *model.Filters
func (_e *HandlerService_Expecter) ListManufacturers(ctx interface{}, filters interface{}) *HandlerService_ListManufacturers_Call {
	return &HandlerService_ListManufacturers_Call{Call: _e.mock.On("ListManufacturers", ctx, filters)}
}

func (_c *HandlerService_ListManufacturers_Call) Run(run func(ctx context.Context, filters *model.Filters)) *HandlerService_ListManufacturers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Filters))
	})
	return _c
}

func (_c *HandlerService_ListManufacturers_Call) Return(_a0 []string, _a1 error) *HandlerService_ListManufacturers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_ListManufacturers_Call) RunAndReturn(run func(context.Context, *model.Filters) ([]string, error)) *HandlerService_ListManufacturers_Call {
	_c.Call.Return(run)
	return _c
}

// ListManufacturersAttachments provides a mock function with given fields: ctx, repo, authorName, manufacturerName
func (_m *HandlerService) ListManufacturersAttachments(ctx context.Context, repo string, authorName string, manufacturerName string) ([]model.FoundAttachment, error) {
	ret := _m.Called(ctx, repo, authorName, manufacturerName)

	if len(ret) == 0 {
		panic("no return value specified for ListManufacturersAttachments")
	}

	var r0 []model.FoundAttachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]model.FoundAttachment, error)); ok {
		return rf(ctx, repo, authorName, manufacturerName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []model.FoundAttachment); ok {
		r0 = rf(ctx, repo, authorName, manufacturerName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FoundAttachment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, repo, authorName, manufacturerName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_ListManufacturersAttachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListManufacturersAttachments'
type HandlerService_ListManufacturersAttachments_Call struct {
	*mock.Call
}

// ListManufacturersAttachments is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - authorName string
//   - manufacturerName string
func (_e *HandlerService_Expecter) ListManufacturersAttachments(ctx interface{}, repo interface{}, authorName interface{}, manufacturerName interface{}) *HandlerService_ListManufacturersAttachments_Call {
	return &HandlerService_ListManufacturersAttachments_Call{Call: _e.mock.On("ListManufacturersAttachments", ctx, repo, authorName, manufacturerName)}
}

func (_c *HandlerService_ListManufacturersAttachments_Call) Run(run func(ctx context.Context, repo string, authorName string, manufacturerName string)) *HandlerService_ListManufacturersAttachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *HandlerService_ListManufacturersAttachments_Call) Return(_a0 []model.FoundAttachment, _a1 error) *HandlerService_ListManufacturersAttachments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_ListManufacturersAttachments_Call) RunAndReturn(run func(context.Context, string, string, string) ([]model.FoundAttachment, error)) *HandlerService_ListManufacturersAttachments_Call {
	_c.Call.Return(run)
	return _c
}

// ListMpns provides a mock function with given fields: ctx, filters
func (_m *HandlerService) ListMpns(ctx context.Context, filters *model.Filters) ([]string, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListMpns")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) ([]string, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) []string); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Filters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_ListMpns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMpns'
type HandlerService_ListMpns_Call struct {
	*mock.Call
}

// ListMpns is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *model.Filters
func (_e *HandlerService_Expecter) ListMpns(ctx interface{}, filters interface{}) *HandlerService_ListMpns_Call {
	return &HandlerService_ListMpns_Call{Call: _e.mock.On("ListMpns", ctx, filters)}
}

func (_c *HandlerService_ListMpns_Call) Run(run func(ctx context.Context, filters *model.Filters)) *HandlerService_ListMpns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Filters))
	})
	return _c
}

func (_c *HandlerService_ListMpns_Call) Return(_a0 []string, _a1 error) *HandlerService_ListMpns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_ListMpns_Call) RunAndReturn(run func(context.Context, *model.Filters) ([]string, error)) *HandlerService_ListMpns_Call {
	_c.Call.Return(run)
	return _c
}

// ListRepos provides a mock function with given fields: ctx
func (_m *HandlerService) ListRepos(ctx context.Context) ([]model.RepoDescription, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRepos")
	}

	var r0 []model.RepoDescription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.RepoDescription, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.RepoDescription); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RepoDescription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_ListRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRepos'
type HandlerService_ListRepos_Call struct {
	*mock.Call
}

// ListRepos is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HandlerService_Expecter) ListRepos(ctx interface{}) *HandlerService_ListRepos_Call {
	return &HandlerService_ListRepos_Call{Call: _e.mock.On("ListRepos", ctx)}
}

func (_c *HandlerService_ListRepos_Call) Run(run func(ctx context.Context)) *HandlerService_ListRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HandlerService_ListRepos_Call) Return(_a0 []model.RepoDescription, _a1 error) *HandlerService_ListRepos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_ListRepos_Call) RunAndReturn(run func(context.Context) ([]model.RepoDescription, error)) *HandlerService_ListRepos_Call {
	_c.Call.Return(run)
	return _c
}

// ListTMIDAttachmentsByID provides a mock function with given fields: ctx, repo, tmID
func (_m *HandlerService) ListTMIDAttachmentsByID(ctx context.Context, repo string, tmID string) ([]model.FoundAttachment, error) {
	ret := _m.Called(ctx, repo, tmID)

	if len(ret) == 0 {
		panic("no return value specified for ListTMIDAttachmentsByID")
	}

	var r0 []model.FoundAttachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.FoundAttachment, error)); ok {
		return rf(ctx, repo, tmID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.FoundAttachment); ok {
		r0 = rf(ctx, repo, tmID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FoundAttachment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, repo, tmID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_ListTMIDAttachmentsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTMIDAttachmentsByID'
type HandlerService_ListTMIDAttachmentsByID_Call struct {
	*mock.Call
}

// ListTMIDAttachmentsByID is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - tmID string
func (_e *HandlerService_Expecter) ListTMIDAttachmentsByID(ctx interface{}, repo interface{}, tmID interface{}) *HandlerService_ListTMIDAttachmentsByID_Call {
	return &HandlerService_ListTMIDAttachmentsByID_Call{Call: _e.mock.On("ListTMIDAttachmentsByID", ctx, repo, tmID)}
}

func (_c *HandlerService_ListTMIDAttachmentsByID_Call) Run(run func(ctx context.Context, repo string, tmID string)) *HandlerService_ListTMIDAttachmentsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *HandlerService_ListTMIDAttachmentsByID_Call) Return(_a0 []model.FoundAttachment, _a1 error) *HandlerService_ListTMIDAttachmentsByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_ListTMIDAttachmentsByID_Call) RunAndReturn(run func(context.Context, string, string) ([]model.FoundAttachment, error)) *HandlerService_ListTMIDAttachmentsByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListTMNameAttachmentsByName provides a mock function with given fields: ctx, repo, tmName
func (_m *HandlerService) ListTMNameAttachmentsByName(ctx context.Context, repo string, tmName string) ([]model.FoundAttachment, error) {
	ret := _m.Called(ctx, repo, tmName)

	if len(ret) == 0 {
		panic("no return value specified for ListTMNameAttachmentsByName")
	}

	var r0 []model.FoundAttachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.FoundAttachment, error)); ok {
		return rf(ctx, repo, tmName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.FoundAttachment); ok {
		r0 = rf(ctx, repo, tmName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FoundAttachment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, repo, tmName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_ListTMNameAttachmentsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTMNameAttachmentsByName'
type HandlerService_ListTMNameAttachmentsByName_Call struct {
	*mock.Call
}

// ListTMNameAttachmentsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - tmName string
func (_e *HandlerService_Expecter) ListTMNameAttachmentsByName(ctx interface{}, repo interface{}, tmName interface{}) *HandlerService_ListTMNameAttachmentsByName_Call {
	return &HandlerService_ListTMNameAttachmentsByName_Call{Call: _e.mock.On("ListTMNameAttachmentsByName", ctx, repo, tmName)}
}

func (_c *HandlerService_ListTMNameAttachmentsByName_Call) Run(run func(ctx context.Context, repo string, tmName string)) *HandlerService_ListTMNameAttachmentsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *HandlerService_ListTMNameAttachmentsByName_Call) Return(_a0 []model.FoundAttachment, _a1 error) *HandlerService_ListTMNameAttachmentsByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_ListTMNameAttachmentsByName_Call) RunAndReturn(run func(context.Context, string, string) ([]model.FoundAttachment, error)) *HandlerService_ListTMNameAttachmentsByName_Call {
	_c.Call.Return(run)
	return _c
}

// SearchInventory provides a mock function with given fields: ctx, repo, query, offset, limit
func (_m *HandlerService) SearchInventory(ctx context.Context, repo string, query string, offset int, limit int) (*model.SearchResult, error) {
	ret := _m.Called(ctx, repo, query, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchInventory")
	}

	var r0 *model.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) (*model.SearchResult, error)); ok {
		return rf(ctx, repo, query, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) *model.SearchResult); ok {
		r0 = rf(ctx, repo, query, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = rf(ctx, repo, query, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerService_SearchInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchInventory'
type HandlerService_SearchInventory_Call struct {
	*mock.Call
}

// SearchInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - query string
//   - offset int
//   - limit int
func (_e *HandlerService_Expecter) SearchInventory(ctx interface{}, repo interface{}, query interface{}, offset interface{}, limit interface{}) *HandlerService_SearchInventory_Call {
	return &HandlerService_SearchInventory_Call{Call: _e.mock.On("SearchInventory", ctx, repo, query, offset, limit)}
}

func (_c *HandlerService_SearchInventory_Call) Run(run func(ctx context.Context, repo string, query string, offset int, limit int)) *HandlerService_SearchInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *HandlerService_SearchInventory_Call) Return(_a0 *model.SearchResult, _a1 error) *HandlerService_SearchInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerService_SearchInventory_Call) RunAndReturn(run func(context.Context, string, string, int, int) (*model.SearchResult, error)) *HandlerService_SearchInventory_Call {
	_c.Call.Return(run)
	return _c
}

// NewHandlerService creates a new instance of HandlerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandlerService {
	mock := &HandlerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
