// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wot-oss/tmc/internal/model"

	repos "github.com/wot-oss/tmc/internal/repos"
)

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// CanonicalRoot provides a mock function with no fields
func (_m *MockRepo) CanonicalRoot() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanonicalRoot")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockRepo_CanonicalRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanonicalRoot'
type MockRepo_CanonicalRoot_Call struct {
	*mock.Call
}

// CanonicalRoot is a helper method to define mock.On call
func (_e *MockRepo_Expecter) CanonicalRoot() *MockRepo_CanonicalRoot_Call {
	return &MockRepo_CanonicalRoot_Call{Call: _e.mock.On("CanonicalRoot")}
}

func (_c *MockRepo_CanonicalRoot_Call) Run(run func()) *MockRepo_CanonicalRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepo_CanonicalRoot_Call) Return(_a0 string) *MockRepo_CanonicalRoot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_CanonicalRoot_Call) RunAndReturn(run func() string) *MockRepo_CanonicalRoot_Call {
	_c.Call.Return(run)
	return _c
}

// CheckIntegrity provides a mock function with given fields: ctx, filter
func (_m *MockRepo) CheckIntegrity(ctx context.Context, filter model.ResourceFilter) ([]model.CheckResult, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for CheckIntegrity")
	}

	var r0 []model.CheckResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ResourceFilter) ([]model.CheckResult, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ResourceFilter) []model.CheckResult); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CheckResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ResourceFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_CheckIntegrity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckIntegrity'
type MockRepo_CheckIntegrity_Call struct {
	*mock.Call
}

// CheckIntegrity is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.ResourceFilter
func (_e *MockRepo_Expecter) CheckIntegrity(ctx interface{}, filter interface{}) *MockRepo_CheckIntegrity_Call {
	return &MockRepo_CheckIntegrity_Call{Call: _e.mock.On("CheckIntegrity", ctx, filter)}
}

func (_c *MockRepo_CheckIntegrity_Call) Run(run func(ctx context.Context, filter model.ResourceFilter)) *MockRepo_CheckIntegrity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ResourceFilter))
	})
	return _c
}

func (_c *MockRepo_CheckIntegrity_Call) Return(results []model.CheckResult, err error) *MockRepo_CheckIntegrity_Call {
	_c.Call.Return(results, err)
	return _c
}

func (_c *MockRepo_CheckIntegrity_Call) RunAndReturn(run func(context.Context, model.ResourceFilter) ([]model.CheckResult, error)) *MockRepo_CheckIntegrity_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRepo) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockRepo_Delete_Call {
	return &MockRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepo_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepo_Delete_Call) Return(_a0 error) *MockRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAttachment provides a mock function with given fields: ctx, container, attachmentName
func (_m *MockRepo) DeleteAttachment(ctx context.Context, container model.AttachmentContainerRef, attachmentName string) error {
	ret := _m.Called(ctx, container, attachmentName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttachment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AttachmentContainerRef, string) error); ok {
		r0 = rf(ctx, container, attachmentName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_DeleteAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttachment'
type MockRepo_DeleteAttachment_Call struct {
	*mock.Call
}

// DeleteAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - container model.AttachmentContainerRef
//   - attachmentName string
func (_e *MockRepo_Expecter) DeleteAttachment(ctx interface{}, container interface{}, attachmentName interface{}) *MockRepo_DeleteAttachment_Call {
	return &MockRepo_DeleteAttachment_Call{Call: _e.mock.On("DeleteAttachment", ctx, container, attachmentName)}
}

func (_c *MockRepo_DeleteAttachment_Call) Run(run func(ctx context.Context, container model.AttachmentContainerRef, attachmentName string)) *MockRepo_DeleteAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.AttachmentContainerRef), args[2].(string))
	})
	return _c
}

func (_c *MockRepo_DeleteAttachment_Call) Return(_a0 error) *MockRepo_DeleteAttachment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_DeleteAttachment_Call) RunAndReturn(run func(context.Context, model.AttachmentContainerRef, string) error) *MockRepo_DeleteAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function with given fields: ctx, id
func (_m *MockRepo) Fetch(ctx context.Context, id string) (string, []byte, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 string
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, []byte, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) []byte); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepo_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockRepo_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepo_Expecter) Fetch(ctx interface{}, id interface{}) *MockRepo_Fetch_Call {
	return &MockRepo_Fetch_Call{Call: _e.mock.On("Fetch", ctx, id)}
}

func (_c *MockRepo_Fetch_Call) Run(run func(ctx context.Context, id string)) *MockRepo_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepo_Fetch_Call) Return(_a0 string, _a1 []byte, _a2 error) *MockRepo_Fetch_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepo_Fetch_Call) RunAndReturn(run func(context.Context, string) (string, []byte, error)) *MockRepo_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAttachment provides a mock function with given fields: ctx, container, attachmentName
func (_m *MockRepo) FetchAttachment(ctx context.Context, container model.AttachmentContainerRef, attachmentName string) ([]byte, error) {
	ret := _m.Called(ctx, container, attachmentName)

	if len(ret) == 0 {
		panic("no return value specified for FetchAttachment")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AttachmentContainerRef, string) ([]byte, error)); ok {
		return rf(ctx, container, attachmentName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.AttachmentContainerRef, string) []byte); ok {
		r0 = rf(ctx, container, attachmentName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.AttachmentContainerRef, string) error); ok {
		r1 = rf(ctx, container, attachmentName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_FetchAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAttachment'
type MockRepo_FetchAttachment_Call struct {
	*mock.Call
}

// FetchAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - container model.AttachmentContainerRef
//   - attachmentName string
func (_e *MockRepo_Expecter) FetchAttachment(ctx interface{}, container interface{}, attachmentName interface{}) *MockRepo_FetchAttachment_Call {
	return &MockRepo_FetchAttachment_Call{Call: _e.mock.On("FetchAttachment", ctx, container, attachmentName)}
}

func (_c *MockRepo_FetchAttachment_Call) Run(run func(ctx context.Context, container model.AttachmentContainerRef, attachmentName string)) *MockRepo_FetchAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.AttachmentContainerRef), args[2].(string))
	})
	return _c
}

func (_c *MockRepo_FetchAttachment_Call) Return(_a0 []byte, _a1 error) *MockRepo_FetchAttachment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_FetchAttachment_Call) RunAndReturn(run func(context.Context, model.AttachmentContainerRef, string) ([]byte, error)) *MockRepo_FetchAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// GetTMMetadata provides a mock function with given fields: ctx, tmID
func (_m *MockRepo) GetTMMetadata(ctx context.Context, tmID string) ([]model.FoundVersion, error) {
	ret := _m.Called(ctx, tmID)

	if len(ret) == 0 {
		panic("no return value specified for GetTMMetadata")
	}

	var r0 []model.FoundVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.FoundVersion, error)); ok {
		return rf(ctx, tmID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.FoundVersion); ok {
		r0 = rf(ctx, tmID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FoundVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tmID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetTMMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTMMetadata'
type MockRepo_GetTMMetadata_Call struct {
	*mock.Call
}

// GetTMMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - tmID string
func (_e *MockRepo_Expecter) GetTMMetadata(ctx interface{}, tmID interface{}) *MockRepo_GetTMMetadata_Call {
	return &MockRepo_GetTMMetadata_Call{Call: _e.mock.On("GetTMMetadata", ctx, tmID)}
}

func (_c *MockRepo_GetTMMetadata_Call) Run(run func(ctx context.Context, tmID string)) *MockRepo_GetTMMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepo_GetTMMetadata_Call) Return(_a0 []model.FoundVersion, _a1 error) *MockRepo_GetTMMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetTMMetadata_Call) RunAndReturn(run func(context.Context, string) ([]model.FoundVersion, error)) *MockRepo_GetTMMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// Import provides a mock function with given fields: ctx, id, raw, opts
func (_m *MockRepo) Import(ctx context.Context, id model.TMID, raw []byte, opts repos.ImportOptions) (repos.ImportResult, error) {
	ret := _m.Called(ctx, id, raw, opts)

	if len(ret) == 0 {
		panic("no return value specified for Import")
	}

	var r0 repos.ImportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TMID, []byte, repos.ImportOptions) (repos.ImportResult, error)); ok {
		return rf(ctx, id, raw, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TMID, []byte, repos.ImportOptions) repos.ImportResult); ok {
		r0 = rf(ctx, id, raw, opts)
	} else {
		r0 = ret.Get(0).(repos.ImportResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TMID, []byte, repos.ImportOptions) error); ok {
		r1 = rf(ctx, id, raw, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_Import_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Import'
type MockRepo_Import_Call struct {
	*mock.Call
}

// Import is a helper method to define mock.On call
//   - ctx context.Context
//   - id model.TMID
//   - raw []byte
//   - opts repos.ImportOptions
func (_e *MockRepo_Expecter) Import(ctx interface{}, id interface{}, raw interface{}, opts interface{}) *MockRepo_Import_Call {
	return &MockRepo_Import_Call{Call: _e.mock.On("Import", ctx, id, raw, opts)}
}

func (_c *MockRepo_Import_Call) Run(run func(ctx context.Context, id model.TMID, raw []byte, opts repos.ImportOptions)) *MockRepo_Import_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TMID), args[2].([]byte), args[3].(repos.ImportOptions))
	})
	return _c
}

func (_c *MockRepo_Import_Call) Return(_a0 repos.ImportResult, _a1 error) *MockRepo_Import_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_Import_Call) RunAndReturn(run func(context.Context, model.TMID, []byte, repos.ImportOptions) (repos.ImportResult, error)) *MockRepo_Import_Call {
	_c.Call.Return(run)
	return _c
}

// ImportAttachment provides a mock function with given fields: ctx, container, attachment, content, force
func (_m *MockRepo) ImportAttachment(ctx context.Context, container model.AttachmentContainerRef, attachment model.Attachment, content []byte, force bool) error {
	ret := _m.Called(ctx, container, attachment, content, force)

	if len(ret) == 0 {
		panic("no return value specified for ImportAttachment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AttachmentContainerRef, model.Attachment, []byte, bool) error); ok {
		r0 = rf(ctx, container, attachment, content, force)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_ImportAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportAttachment'
type MockRepo_ImportAttachment_Call struct {
	*mock.Call
}

// ImportAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - container model.AttachmentContainerRef
//   - attachment model.Attachment
//   - content []byte
//   - force bool
func (_e *MockRepo_Expecter) ImportAttachment(ctx interface{}, container interface{}, attachment interface{}, content interface{}, force interface{}) *MockRepo_ImportAttachment_Call {
	return &MockRepo_ImportAttachment_Call{Call: _e.mock.On("ImportAttachment", ctx, container, attachment, content, force)}
}

func (_c *MockRepo_ImportAttachment_Call) Run(run func(ctx context.Context, container model.AttachmentContainerRef, attachment model.Attachment, content []byte, force bool)) *MockRepo_ImportAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.AttachmentContainerRef), args[2].(model.Attachment), args[3].([]byte), args[4].(bool))
	})
	return _c
}

func (_c *MockRepo_ImportAttachment_Call) Return(_a0 error) *MockRepo_ImportAttachment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_ImportAttachment_Call) RunAndReturn(run func(context.Context, model.AttachmentContainerRef, model.Attachment, []byte, bool) error) *MockRepo_ImportAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function with given fields: ctx, updatedIds
func (_m *MockRepo) Index(ctx context.Context, updatedIds ...string) error {
	_va := make([]interface{}, len(updatedIds))
	for _i := range updatedIds {
		_va[_i] = updatedIds[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, updatedIds...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MockRepo_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - ctx context.Context
//   - updatedIds ...string
func (_e *MockRepo_Expecter) Index(ctx interface{}, updatedIds ...interface{}) *MockRepo_Index_Call {
	return &MockRepo_Index_Call{Call: _e.mock.On("Index",
		append([]interface{}{ctx}, updatedIds...)...)}
}

func (_c *MockRepo_Index_Call) Run(run func(ctx context.Context, updatedIds ...string)) *MockRepo_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockRepo_Index_Call) Return(_a0 error) *MockRepo_Index_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_Index_Call) RunAndReturn(run func(context.Context, ...string) error) *MockRepo_Index_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, search
func (_m *MockRepo) List(ctx context.Context, search *model.Filters) (model.SearchResult, error) {
	ret := _m.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 model.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) (model.SearchResult, error)); ok {
		return rf(ctx, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) model.SearchResult); ok {
		r0 = rf(ctx, search)
	} else {
		r0 = ret.Get(0).(model.SearchResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Filters) error); ok {
		r1 = rf(ctx, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - search *model.Filters
func (_e *MockRepo_Expecter) List(ctx interface{}, search interface{}) *MockRepo_List_Call {
	return &MockRepo_List_Call{Call: _e.mock.On("List", ctx, search)}
}

func (_c *MockRepo_List_Call) Run(run func(ctx context.Context, search *model.Filters)) *MockRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Filters))
	})
	return _c
}

func (_c *MockRepo_List_Call) Return(_a0 model.SearchResult, _a1 error) *MockRepo_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_List_Call) RunAndReturn(run func(context.Context, *model.Filters) (model.SearchResult, error)) *MockRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListCompletions provides a mock function with given fields: ctx, kind, args, toComplete
func (_m *MockRepo) ListCompletions(ctx context.Context, kind string, args []string, toComplete string) ([]string, error) {
	ret := _m.Called(ctx, kind, args, toComplete)

	if len(ret) == 0 {
		panic("no return value specified for ListCompletions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, string) ([]string, error)); ok {
		return rf(ctx, kind, args, toComplete)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, string) []string); ok {
		r0 = rf(ctx, kind, args, toComplete)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, string) error); ok {
		r1 = rf(ctx, kind, args, toComplete)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_ListCompletions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCompletions'
type MockRepo_ListCompletions_Call struct {
	*mock.Call
}

// ListCompletions is a helper method to define mock.On call
//   - ctx context.Context
//   - kind string
//   - args []string
//   - toComplete string
func (_e *MockRepo_Expecter) ListCompletions(ctx interface{}, kind interface{}, args interface{}, toComplete interface{}) *MockRepo_ListCompletions_Call {
	return &MockRepo_ListCompletions_Call{Call: _e.mock.On("ListCompletions", ctx, kind, args, toComplete)}
}

func (_c *MockRepo_ListCompletions_Call) Run(run func(ctx context.Context, kind string, args []string, toComplete string)) *MockRepo_ListCompletions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(string))
	})
	return _c
}

func (_c *MockRepo_ListCompletions_Call) Return(_a0 []string, _a1 error) *MockRepo_ListCompletions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_ListCompletions_Call) RunAndReturn(run func(context.Context, string, []string, string) ([]string, error)) *MockRepo_ListCompletions_Call {
	_c.Call.Return(run)
	return _c
}

// Spec provides a mock function with no fields
func (_m *MockRepo) Spec() model.RepoSpec {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Spec")
	}

	var r0 model.RepoSpec
	if rf, ok := ret.Get(0).(func() model.RepoSpec); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.RepoSpec)
	}

	return r0
}

// MockRepo_Spec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spec'
type MockRepo_Spec_Call struct {
	*mock.Call
}

// Spec is a helper method to define mock.On call
func (_e *MockRepo_Expecter) Spec() *MockRepo_Spec_Call {
	return &MockRepo_Spec_Call{Call: _e.mock.On("Spec")}
}

func (_c *MockRepo_Spec_Call) Run(run func()) *MockRepo_Spec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepo_Spec_Call) Return(_a0 model.RepoSpec) *MockRepo_Spec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_Spec_Call) RunAndReturn(run func() model.RepoSpec) *MockRepo_Spec_Call {
	_c.Call.Return(run)
	return _c
}

// Versions provides a mock function with given fields: ctx, name
func (_m *MockRepo) Versions(ctx context.Context, name string) ([]model.FoundVersion, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Versions")
	}

	var r0 []model.FoundVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.FoundVersion, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.FoundVersion); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FoundVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_Versions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Versions'
type MockRepo_Versions_Call struct {
	*mock.Call
}

// Versions is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRepo_Expecter) Versions(ctx interface{}, name interface{}) *MockRepo_Versions_Call {
	return &MockRepo_Versions_Call{Call: _e.mock.On("Versions", ctx, name)}
}

func (_c *MockRepo_Versions_Call) Run(run func(ctx context.Context, name string)) *MockRepo_Versions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepo_Versions_Call) Return(_a0 []model.FoundVersion, _a1 error) *MockRepo_Versions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_Versions_Call) RunAndReturn(run func(context.Context, string) ([]model.FoundVersion, error)) *MockRepo_Versions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
